// Generates src/art/fontMetrics.ts: advance widths of the UI fonts (Inter for
// text, Cormorant SC for headings), measured in Chromium from the bundled
// @fontsource files, so text fitting (src/ui/textfit.ts) runs without a browser.
// Usage: node scripts/font-metrics.mjs   (re-run after changing a font or weight)
import { chromium } from 'playwright';
import { readFileSync, writeFileSync } from 'node:fs';

const FACES = {
  body: { family: 'Inter', weight: 500, files: ['inter/files/inter-latin-500-normal.woff2', 'inter/files/inter-cyrillic-500-normal.woff2', 'inter/files/inter-latin-ext-500-normal.woff2'] },
  head: { family: 'Cormorant SC', weight: 700, files: ['cormorant-sc/files/cormorant-sc-latin-700-normal.woff2', 'cormorant-sc/files/cormorant-sc-cyrillic-700-normal.woff2', 'cormorant-sc/files/cormorant-sc-latin-ext-700-normal.woff2'] },
};

// Every character the old pixel font drew, plus the rest of printable ASCII, Russian and UI typography.
const src = readFileSync('src/art/font.ts', 'utf8');
const chars = new Set();
for (const m of src.matchAll(/^ {2}(?:'((?:\\'|[^'])+)'|([^\s:'/]+)):/gm)) chars.add((m[1] ?? m[2]).replace("\\'", "'"));
for (let c = 32; c < 127; c++) chars.add(String.fromCharCode(c));
for (let c = 0x410; c <= 0x44f; c++) chars.add(String.fromCharCode(c));
for (const c of 'ЁёІіЇїЄє…–—«»“”„‘’·•×÷±→←↑↓№%‰€$£°') chars.add(c);
const list = [...chars].filter((c) => [...c].length === 1);

const b64 = (f) => readFileSync(`node_modules/@fontsource/${f}`).toString('base64');
const css = Object.values(FACES)
  .flatMap((f) => f.files.map((file) => `@font-face{font-family:'${f.family}';font-weight:${f.weight};src:url(data:font/woff2;base64,${b64(file)}) format('woff2');}`))
  .join('\n');

const browser = await chromium.launch();
const page = await browser.newPage();
await page.setContent(`<style>${css}</style><body></body>`);
const out = await page.evaluate(
  async ({ faces, list }) => {
    const res = {};
    for (const [key, f] of Object.entries(faces)) {
      const font = `${f.weight} 1000px '${f.family}'`;
      await document.fonts.load(font, list.join(''));
      const ctx = document.createElement('canvas').getContext('2d');
      ctx.font = font;
      const adv = {};
      for (const ch of list) adv[ch] = Math.round(ctx.measureText(ch).width);
      const m = ctx.measureText('H');
      res[key] = { adv, cap: Math.round(m.actualBoundingBoxAscent), check: document.fonts.check(font, 'Hж') };
    }
    return res;
  },
  { faces: FACES, list },
);
await browser.close();
for (const [k, v] of Object.entries(out)) if (!v.check) throw new Error(`font ${k} did not load`);

const lines = [
  '// Generated by scripts/font-metrics.mjs from the bundled @fontsource fonts. Do not edit.',
  '// Advance widths per character in 1/1000 em; `cap` is the cap height in 1/1000 em.',
  '',
  ...Object.entries(out).map(
    ([k, v]) => `export const ${k.toUpperCase()}_METRICS: { cap: number; adv: Record<string, number> } = ${JSON.stringify({ cap: v.cap, adv: v.adv })};`,
  ),
  '',
];
writeFileSync('src/art/fontMetrics.ts', lines.join('\n'));
console.log('wrote src/art/fontMetrics.ts', list.length, 'chars');
